<?php

return [
    'account' => ['create', 'view', 'edit', 'delete', 'export'],
    'account category' => ['create', 'view', 'edit', 'delete', 'export'],
    'account note' => ['create', 'view', 'edit', 'delete'],
    'expense' => ['create', 'view', 'edit', 'delete', 'export'],
    'income' => ['create', 'view', 'edit', 'delete', 'export'],
    'general voucher' => ['create', 'view', 'edit', 'delete', 'export'],
    'cheque' => ['create', 'view', 'edit', 'delete', 'print'],
    'customer' => ['create', 'view', 'edit', 'delete', 'export'],
    'customer type' => ['create', 'view', 'edit', 'delete'],
    'country' => ['create', 'view', 'edit', 'delete'],
    'vendor' => ['create', 'view', 'edit', 'delete', 'export'],
    'user' => ['create', 'view', 'edit', 'delete'],
    'employee' => ['create', 'view', 'edit', 'delete', 'export'],
    'employee attendance' => ['create', 'view', 'modify', 'export'],
    'employee commission' => ['create', 'view', 'edit', 'delete'],
    'role' => ['create', 'view', 'edit', 'delete', 'permissions'],
    'branch' => ['create', 'view', 'edit', 'delete'],
    'product' => ['create', 'view', 'edit', 'delete', 'import', 'export'],
    'service' => ['create', 'view', 'edit', 'delete', 'import', 'export'],
    'combo offer' => ['create', 'view', 'edit', 'delete'],
    'package category' => ['create', 'view', 'edit', 'delete'],
    'package' => [
        'create', 'view', 'edit', 'delete',
        'dashboard package calendar',
    ],
    'inventory' => [
        'view', 'edit', 'delete', 'import', 'export',
        'dashboard status',
        'product search',
        'barcode cart',
        'transfer',
        'opening balance',
        'reset stock',
        'stock check',
    ],
    'inventory transfer' => ['create', 'view', 'edit', 'edit completed', 'delete', 'import', 'export'],
    'category' => ['create', 'view', 'edit', 'delete', 'import', 'export'],
    'appointment' => ['create', 'view', 'edit', 'delete', 'export', 'checkout', 'dashboard'],
    'sale' => [
        'create', 'view', 'edit', 'edit completed', 'delete item after completed', 'delete', 'cancel', 'import', 'export', 'receipts', 'view journal entries', 'dashboard bar chart',
        'item price edit',
        'dashboard weekly summary',
        'dashboard top items',
        'audit view',
        'combo offer',
        'feedback',
        'change day session',
    ],
    'sales return' => ['create', 'view', 'edit', 'edit completed', 'delete', 'export', 'payments', 'view journal entries'],
    'purchase' => [
        'create', 'view', 'edit', 'edit completed', 'delete', 'cancel',
        'export',
        'payments',
        'view journal entries',
        'delete item after completed',
        'delete payment after completed',
        'barcode print',
        'purchase note print',
    ],
    'purchase return' => ['create', 'view', 'edit', 'edit completed', 'delete', 'cancel', 'export', 'view journal entries'],
    'unit' => ['create', 'view', 'edit', 'delete'],
    'designation' => ['create', 'view', 'edit', 'delete'],
    'department' => ['create', 'view', 'edit', 'delete'],
    'brand' => ['create', 'view', 'edit', 'delete'],
    'whatsapp' => ['integration'],
    'report' => [
        'income vs expense dashboard pie chart',
        'income vs expense dashboard bar chart',
        'sale item',
        'sale return item',
        'day book',
        'day book export',
        'daily sales insights',
        'sales overview',
        'purchase item',
        'customer',
        'employee',
        'product',
        'profit loss',
        'trial balance',
        'balance sheet',
        'stock analysis',
        'employee productivity',
        'customer callback reminder',
        'sale calendar',
        'sale and sales return items',
        'day wise sale',
        'bank reconciliation report',
        'customer aging',
        'vendor aging',
        'tax report',
        'day wise tax report',
    ],
    'log' => ['inventory'],
    'day close' => ['sync amount'],
    'api_log' => ['view', 'moq settings'],
    'backup' => ['create', 'view', 'download'],
    'system health' => ['view'],
    'visitor analytics' => ['view'],
    'configuration' => ['barcode', 'settings', 'cheque'],
];
