<?php

return [
    'account' => ['create', 'view', 'edit', 'delete', 'export'],
    'account category' => ['create', 'view', 'edit', 'delete', 'export'],
    'account note' => ['create', 'view', 'edit', 'delete'],
    'expense' => ['create', 'view', 'edit', 'delete', 'import', 'export'],
    'income' => ['create', 'view', 'edit', 'delete', 'import', 'export'],
    'general voucher' => ['create', 'view', 'edit', 'delete', 'export'],
    'cheque' => ['create', 'view', 'edit', 'delete', 'print'],
    'customer' => ['create', 'view', 'edit', 'delete', 'import', 'export'],
    'customer kyc' => ['view', 'edit', 'confirm', 'print'],
    'customer type' => ['create', 'view', 'edit', 'delete'],
    'country' => ['create', 'view', 'edit', 'delete'],
    'vendor' => ['create', 'view', 'edit', 'delete', 'import', 'export', 'print', 'payment reverse'],
    'user' => ['create', 'view', 'edit', 'delete', 'impersonate'],
    'employee' => ['create', 'view', 'edit', 'delete', 'export'],
    'employee attendance' => ['create', 'view', 'modify', 'export'],
    'employee commission' => ['create', 'view', 'edit', 'delete'],
    'role' => ['create', 'view', 'edit', 'delete', 'permissions'],
    'branch' => ['create', 'view', 'edit', 'delete'],
    'product' => ['create', 'view', 'edit', 'delete', 'import', 'export', 'ai image generation'],
    'asset' => ['create', 'view', 'edit', 'delete', 'import', 'export', 'dispose', 'post depreciation', 'view accounting', 'dashboard overview'],
    'service' => ['create', 'view', 'edit', 'delete', 'import', 'export'],
    'combo offer' => ['create', 'view', 'edit', 'delete'],
    'package category' => ['create', 'view', 'edit', 'delete'],
    'package' => [
        'create',
        'view',
        'edit',
        'delete',
        'dashboard package calendar',
    ],
    'inventory' => [
        'view',
        'edit',
        'delete',
        'import',
        'export',
        'dashboard status',
        'product search',
        'barcode cart',
        'transfer',
        'stock adjustment',
        'reset stock',
        'stock check',
    ],
    'inventory transfer' => ['create', 'view', 'edit', 'edit completed', 'delete', 'import', 'export'],
    'issue' => ['create', 'view', 'edit', 'delete', 'print'],
    'ticket' => ['create', 'view', 'edit', 'delete', 'comment'],
    'day session' => ['create', 'view', 'list', 'print'],
    'category' => ['create', 'view', 'edit', 'delete', 'import', 'export'],
    'appointment' => ['create', 'view', 'edit', 'delete', 'export', 'checkout', 'dashboard'],
    'sale' => [
        'create',
        'view',
        'edit',
        'edit completed',
        'delete item after completed',
        'delete',
        'cancel',
        'import',
        'export',
        'receipts',
        'view journal entries',
        'dashboard bar chart',
        'item price edit',
        'dashboard weekly summary',
        'dashboard top items',
        'audit view',
        'combo offer',
        'feedback',
        'change day session',
    ],
    'sales return' => ['create', 'view', 'edit', 'edit completed', 'delete', 'cancel', 'export', 'payments', 'receipts', 'view journal entries'],
    'purchase' => [
        'create',
        'view',
        'edit',
        'edit completed',
        'delete',
        'cancel',
        'export',
        'payments',
        'view journal entries',
        'delete item after completed',
        'delete payment after completed',
        'barcode print',
        'purchase note print',
    ],
    'purchase return' => ['create', 'view', 'edit', 'edit completed', 'delete', 'cancel', 'export', 'payments', 'view journal entries'],
    'unit' => ['create', 'view', 'edit', 'delete'],
    'designation' => ['create', 'view', 'edit', 'delete'],
    'rack' => ['create', 'view', 'edit', 'delete'],
    'department' => ['create', 'view', 'edit', 'delete'],
    'brand' => ['create', 'view', 'edit', 'delete'],
    'whatsapp' => ['integration'],
    'report' => [
        'income vs expense dashboard pie chart',
        'income vs expense dashboard bar chart',
        'sale item',
        'sale return item',
        'purchase return item',
        'day book',
        'day book export',
        'daily sales insights',
        'sales overview',
        'purchase item',
        'customer',
        'employee',
        'product',
        'profit loss',
        'profit loss statement',
        'trial balance',
        'balance sheet',
        'stock analysis',
        'employee productivity',
        'customer callback reminder',
        'sale calendar',
        'sale and sales return items',
        'day wise sale',
        'bank reconciliation report',
        'customer aging',
        'vendor aging',
        'tax report',
        'day wise tax report',
        'monthly sale',
        'issue item',
        'issue aging',
        'tailoring order item',
        'tailoring non delivery',
        'tailoring order item tailor',
    ],
    'log' => ['inventory', 'log viewer', 'email'],
    'day close' => ['sync amount'],
    'api_log' => ['view', 'delete', 'moq settings'],
    'backup' => ['create', 'view', 'download'],
    'system health' => ['view'],
    'visitor analytics' => ['view'],
    'configuration' => ['barcode', 'settings', 'cheque'],
    'tailoring category' => ['create', 'view', 'edit', 'delete'],
    'tailoring measurement option' => ['create', 'view', 'edit', 'delete', 'quick add'],
    'tailoring order' => ['view', 'create', 'edit', 'delete', 'export', 'view journal entries', 'receipts'],
    'tailoring job completion' => ['view', 'create', 'edit', 'delete'],

    // Property Management
    'property' => ['create', 'view', 'edit', 'delete', 'export', 'dashboard overview'],
    'property dashboard' => [
        'maintenance overview',
        'complaint overview',
        'financial overview',
        'supply request overview',
        'rent out expiry overview',
    ],
    'property group' => ['create', 'view', 'edit', 'delete'],
    'property building' => ['create', 'view', 'edit', 'delete'],
    'property type' => ['create', 'view', 'edit', 'delete'],
    'utility' => ['create', 'view', 'edit', 'delete'],
    'document type' => ['create', 'view', 'edit', 'delete'],
    'complaint category' => ['create', 'view', 'edit', 'delete'],
    'complaint' => ['create', 'view', 'edit', 'delete'],
    'tenant detail' => ['create', 'view', 'edit', 'delete'],

    // Property Lead Module
    'property lead' => [
        'create',
        'view',
        'edit',
        'delete',
        'download',
        'booking transfer',
        'delete note',
        'dashboard status count',
        'dashboard recent activities',
        'dashboard source pie chart',
        'dashboard employee bar chart',
    ],

    // RentOut - Rent Module
    'rent out' => [
        'create',
        'view',
        'edit',
        'delete',
        'export',
        'vacate',
        'extend',
        'book',
        'cancel',
        'approve',
        'financial approve',
        'complete',
        'view journal entries',
        'payment',
        'transfer payment',
        // Gates every rent-out print document (statement, utilities statement,
        // payment receipt/voucher). Deliberately one permission across both the
        // 'rent out' and 'rent out lease' agreement types, since the print
        // routes are shared and a route can only check a single ability.
        'print',
    ],
    'rent out booking' => [
        'create',
        'view',
        'edit',
        'delete',
        'submitted',
        'financial approved',
        'approved',
        'completed',
        'cancel',
        'confirm',
        'reservation form',
        'residential lease',
    ],
    'rent out security' => ['create', 'view', 'edit', 'delete', 'export'],
    'rent out cheque' => ['create', 'view', 'edit', 'delete', 'update status', 'export'],
    'rent out lease cheque' => ['create', 'view', 'edit', 'delete', 'update status'],
    'rent out utility' => ['create', 'view', 'edit', 'delete', 'export'],
    'rent out service' => ['create', 'view', 'edit', 'delete', 'export'],
    'rent out payment term' => ['create', 'view', 'edit', 'delete', 'export'],
    'rent out note' => ['create', 'view', 'delete'],
    'rent out document' => ['create', 'view', 'edit', 'delete'],
    'rent out checklist' => ['view', 'create', 'edit', 'delete', 'print'],
    'rent out checklist item' => ['create', 'view', 'edit', 'delete', 'import'],

    // Email templates get their OWN group rather than riding on
    // configuration.settings, so template authoring can be delegated to
    // marketing/leasing staff without handing them the whole settings screen.
    'email template' => ['create', 'view', 'edit', 'delete'],

    // Property Appointment Scheduler — customer-scheduled appointments made
    // from a public link sent off a lease/sale agreement.
    'property appointment' => [
        'create',
        'view',
        'edit',
        'delete',
        'export',
        'send link',
        'calendar',
        'manage availability',
    ],

    // RentOut - Lease/Sale Module
    'rent out lease' => [
        'create',
        'view',
        'edit',
        'delete',
        'export',
        'vacate',
        'extend',
        'book',
        'cancel',
        'approve',
        'financial approve',
        'complete',
        'view journal entries',
        'payment',
        'transfer payment',
        'cheque management',
    ],
    'rent out lease booking' => [
        'create',
        'view',
        'edit',
        'delete',
        'submitted',
        'financial approved',
        'approved',
        'completed',
        'cancel',
        'confirm',
        'reservation form',
        'residential lease',
    ],

    // 'view own' narrows a table to the records the user created; the Table
    // components grant it only when the broader 'view' is absent.
    'purchase request' => ['create', 'view', 'view own', 'edit', 'delete', 'decide'],
    'local purchase order' => ['create', 'edit', 'view', 'view own', 'delete', 'decide', 'confirm', 'print', 'payments'],
    'grn' => ['create', 'view', 'view own', 'edit', 'delete', 'decide', 'reverse'],
    'lpo-purchase' => ['create', 'view', 'view own', 'edit', 'delete', 'decide', 'reverse'],

    // Maintenance Module
    'maintenance' => ['create', 'view', 'edit', 'delete', 'export', 'assign', 'complete', 'technician view'],

    // Supply Request Module
    'supply request' => [
        'create',
        'view',
        'edit',
        'delete',
        'payment',
        'delete item',
        'approve',
        'final approve',
        'complete',
        'print',
    ],

    // Trading Platform (FlatTrade) — 'view' gates the screens, 'trade' gates
    // order execution and privileged controls (kill switch, strategies, alerts).
    'flat_trade' => ['view', 'trade', 'connect', 'disconnect'],

    // Task Management Module
    'task-management' => ['view', 'create', 'edit', 'delete', 'add-note'],
];
